### ISSUE TITLE
3.0.1 failure in slightly outdated Chrome

### ISSUE THREAD

**Issue by buu700** [andyet/SimpleWebRTC#603]
After updating from 3.0.0 to 3.0.1, trying to start a video call in Chrome 52 now fails with the error `TypeError: navigator.mediaDevices.getUserMedia is not a function`. (Specifically, Chrome 52.0.2743.98 on Android 5.1.1.)

**Comment by fippo** [comment]
are you including adapter.js (which iirc shims this) alongside simplewebrtc? This is required as of 3.x

**Comment by buu700** [comment]
Oh, right, I forgot about all the other WebRTC modules that this depends on; sorry about that! We are using webrtc-adapter, which I see increased in version from 4.0.2 to 4.2.1 between when this was last confirmed to be working and when this issue was caught, so it sounds like that's the more likely culprit. I'll close this and resubmit there after confirming.

**Comment by fippo** [comment]
I don't recall any changes related to getUserMedia between 4.0.2 and 4.2.1... otoh these days it is quite easy to forget adapter without noticing major things break ;-)

**Comment by buu700** [comment]
Ahh, okay, I found the problem after debugging a bit further. This was a pretty silly problem to have and partially my fault.

https://github.com/andyet/SimpleWebRTC/commit/4b05b5035acdc149e8d19c9c34610c02f00c2f84 is the root cause. Specifically, after the `Can't resolve 'simplewebrtc'` issue caused by 3.0.0 (which I didn't report because I assumed it would be discovered quickly without my adding to the noise), I'd implemented a temporary workaround of copying `out/simplewebrtc-with-adapter.bundle.js` to `simplewebrtc.js`. Because of this, 3.0.1's fix essentially just removed webrtc-adapter from our build. (All in pre-production code, so not a big deal.)
